const data = {
    products: [
      {
        _id: '1',
        name: 'Lugano Classic Watch',
        category: 'Watch',
        image: '/images/p1.jpg',
        price: 200,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Verbier Half Zip Sweater',
        category: 'Shirts',
        image: '/images/p2.jpg',
        price: 55,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Old Money High Suede Loafers',
        category: 'Shoes',
        image: '/images/p3.jpg',
        price: 80,
        brand: 'Lacoste',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Merino Wool Zip Up',
        category: 'Sweater',
        image: '/images/p4.jpg',
        price: 63,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Classic Chic Shirt',
        category: 'Shirt',
        image: '/images/p5.jpg',
        price: 45,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Miami Sunglasses',
        category: 'Sunglasses',
        image: '/images/p6.jpg',
        price: 37,
        brand: 'Adidas',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;